# Generated by Django 3.2.6 on 2021-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_at',
            field=models.DateField(auto_now=True, verbose_name='Последние изменения'),
        ),
    ]
