# Generated by Django 3.2.6 on 2021-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_course_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последние изменения'),
        ),
    ]
