# Generated by Django 3.2.6 on 2021-12-20 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Homework', '0005_alter_homework_lecture_for_homework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_task', models.URLField(verbose_name='Решение')),
                ('mark', models.SmallIntegerField(verbose_name='Оценка')),
                ('task_solved', models.BooleanField(verbose_name='Задача решена?')),
                ('homework_solution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_solution', to='Homework.homework', verbose_name='Домашняя работа')),
                ('user_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solution', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
        ),
    ]
