# Generated by Django 3.2.6 on 2021-12-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homework', '0005_alter_homework_lecture_for_homework'),
        ('Solution', '0002_alter_solution_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='homework_solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_solution', to='Homework.homework', verbose_name='Домашняя работа'),
        ),
    ]
