# Generated by Django 4.0 on 2021-12-21 08:20 (переделал все, в старые миграции не видели Person)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('Lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_task', models.TextField(verbose_name='Домашняя работа')),
                ('title', models.CharField(max_length=155, verbose_name='Название домашней работы')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('lecture_for_homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_for_homework', to='Lecture.lecture', verbose_name='Лекция')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_lec', to='Person.myuser', verbose_name='Автор лекции')),
            ],
        ),
    ]
