# Generated by Django 4.0 on 2021-12-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Solution', '0001_initial'),
        ('Person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.SmallIntegerField(verbose_name='Оценка')),
                ('solution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_solution', to='Solution.solution', verbose_name='Решение')),
                ('user_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mark', to='Person.myuser')),
            ],
        ),
    ]
