# Generated by Django 4.0 on 2021-12-23 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('Mark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Текстовое сообщение')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('mark_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_message', to='Mark.mark', verbose_name='Оценка_ID')),
                ('user_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Person.myuser', verbose_name='Сообщение написал')),
            ],
        ),
    ]
