# Generated by Django 4.0 on 2021-12-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mark', '0002_messageteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageteacher',
            name='user_message',
        ),
    ]
