# Generated by Django 3.2.6 on 2021-12-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecture', '0002_alter_lecture_course'),
        ('Homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='Lecture.lecture', verbose_name='Курсс'),
        ),
    ]
