# Generated by Django 3.2.6 on 2021-12-19 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecture', '0002_alter_lecture_course'),
        ('Homework', '0002_alter_homework_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='lecture_for_homework',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecture_for_homework', to='Lecture.lecture', verbose_name='Курсс'),
            preserve_default=False,
        ),
    ]
