# Generated by Django 4.0 on 2021-12-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachcour',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cou', to='Course.course'),
        ),
        migrations.AlterField(
            model_name='teachcour',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tea', to='Person.myuser'),
        ),
    ]
