# Generated by Django 4.0 on 2021-12-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('Homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_task', models.URLField(verbose_name='Решение')),
                ('mark', models.SmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('task_solved', models.BooleanField(verbose_name='Задача решена?')),
                ('homework_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_solution', to='Homework.homework', verbose_name='Домашняя работа')),
                ('user_solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solution', to='Person.myuser', verbose_name='Студент')),
            ],
        ),
    ]
