# Generated by Django 4.0 on 2021-12-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='mark',
        ),
    ]
